import {createEvent,sanitizePreview,sanitizeSensitiveText} from '../lib/events.js';
const protocol='miniproctor-zcode-sdk-v1',types=new Set(['started','provider','message','result','error']),uuid=(prefix,value)=>typeof value==='string'&&new RegExp('^'+prefix+'[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$','u').test(value);
export const isZCodeSdkFrame=raw=>Boolean(raw&&typeof raw==='object'&&!Array.isArray(raw)&&raw.protocol===protocol&&types.has(raw.type));
export const isZCodeStartedFrame=raw=>isZCodeSdkFrame(raw)&&raw.type==='started'&&uuid('sess_',raw.native_session_id)&&uuid('turn_',raw.native_turn_id)&&raw.native_version==='0.16.9';
export function mapZCodeSdkFrame(raw,{sessionId,sequencer}){if(!isZCodeSdkFrame(raw))return[];const common={sessionId,agentType:'generic',sequencer},failed=code=>[createEvent({...common,eventType:'error',payload:{code:/^zcode-[a-z-]{1,64}$/u.test(code||'')?code:'zcode-native-incomplete',message:'ZCode 任务未正常完成，请检查电脑端配置和连接',severity:'fatal',recoverable:false}})];
  if(raw.type==='provider')return[];if(raw.type==='started')return isZCodeStartedFrame(raw)?[createEvent({...common,eventType:'custom',payload:{custom_type:'zcode_sdk_started',fallback_text:'ZCode 会话已接收任务',data:{native_session_id:raw.native_session_id,native_turn_id:raw.native_turn_id,native_cli_version:raw.native_version}}})]:failed('zcode-native-identity');
  if(raw.type==='message')return typeof raw.text==='string'&&raw.text?[createEvent({...common,eventType:'agent_message',payload:{role:'assistant',content:sanitizeSensitiveText(sanitizePreview(raw.text,32000)),content_type:'text',is_final:false}})]:[];if(raw.type==='error')return failed(raw.code);
  const exited=!raw.error_code&&raw.native_stop?.exited===true&&raw.native_stop.tree_verified===true&&raw.native_stop.remaining_owned_instances===0&&raw.gateway?.closed===true&&raw.gateway.active===0&&raw.runtime?.provider_key_matches===0,identity=uuid('sess_',raw.native_session_id)&&uuid('turn_',raw.native_turn_id);
  if(exited&&identity&&raw.status==='completed'&&raw.native_stop.code===0&&raw.gateway.contacted>0&&raw.gateway.contacted<=2&&raw.gateway.successful===raw.gateway.contacted&&raw.gateway.failed===0&&raw.gateway.rejected===0&&!raw.gateway.quota_exceeded)return[createEvent({...common,eventType:'session_end',payload:{reason:'completed',summary:'ZCode 单轮任务已完成',usage:{}}})];
  const early=raw.gateway?.contacted===0&&(raw.native_stop?.code===null&&raw.native_stop.owned_processes===0&&raw.native_stop.reason==='not-started'||raw.native_stop?.code===0&&raw.native_admission==='not-accepted'&&raw.native_event_count===0);
  if(exited&&raw.status==='cancelled'&&(raw.native_stop.code===0&&identity||early))return[createEvent({...common,eventType:'session_end',payload:{reason:'stopped',summary:'ZCode 任务已停止',usage:{}}})];return failed(raw.error_code);
}
